version: "3"

services:
  web:
    container_name: web
    build: ./app
    ports:
      - "5000:5000"
    links:
      - redis
      - db
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app

  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: redis

  db: 
    image: mysql:5.7
    ports:
        - "32000:3306"
    environment:
        MYSQL_ROOT_PASSWORD: admin
    volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro

  worker:
    build:
      context: ./app
    hostname: worker
    entrypoint: celery
    command: -A app.celery worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis